[tool.poetry]
name = "easytimer"
version = "0.1.0"
description = "Simple customizable Python timer."
readme = "README.md"
license = "MIT"
authors = ["Nibs"]
homepage = "https://github.com/snpm/scraipe"

[tool.poetry.dependencies]
python = ">=3.10"

[tool.poetry.group.dev.dependencies]
pytest = "*"